### ISSUE TITLE
PoS tagging case study: predict help

### ISSUE THREAD

**Issue by gersh0m** [dbamman/latin-bert#2]
Hi,
If I understand  correctly, selecting the test mode of the script ```latin_sequence_labeling.py``` just outputs the test result.
What if someone wants to see the actual result of the pos tagging process?  

If I understand the help on line provided by the script itself, one should perform a 'prediction' on the same file. Something like this:
```
python3 scripts/latin_sequence_labeling.py -m predict --bertPath ../../models/latin_bert --tokenizerPath ../../models/subword_tokenizer_latin/latin.subword.encoder -i UD_Latin-Perseus/la_perseus-ud-test.conllu  -o la_perseus-ud-test.predicted.conllu --tagFile UD_Latin-Perseus/pos.tagset --modelFile UD_Latin-Perseus/pos.model
```

But I get the following error instead:

```
********************************************
Running on: cpu
********************************************

{'mode': 'predict', 'bertPath': '../../models/latin_bert', 'tokenizerPath': '../../models/subword_tokenizer_latin/latin.subword.encoder', 'batch_prediction_file': None, 'input_prediction_file': 'UD_Latin-Perseus/la_perseus-ud-test.conllu', 'output_prediction_file': 'la_perseus-ud-test.predicted.conllu', 'trainFile': None, 'testFile': None, 'devFile': None, 'tagFile': 'UD_Latin-Perseus/pos.tagset', 'modelFile': 'UD_Latin-Perseus/pos.model', 'metric': None, 'max_epochs': None}
{0: 'PRON', 1: 'ADV', 2: 'ADJ', 3: 'VERB', 4: 'NOUN', 5: 'PUNCT', 6: 'CCONJ', 7: 'ADP', 8: 'SCONJ', 9: 'NUM', 10: 'INTJ', 11: 'X'}
Traceback (most recent call last):
  File "scripts/latin_sequence_labeling.py", line 475, in <module>
    score=model.predict(predictFile, tagset, outFile)
  File "scripts/latin_sequence_labeling.py", line 134, in predict
    dev_orig_sentences = sequence_reader.prepare_annotations_from_file(dev_file, tagset, labeled=False)
  File "/home/circse/latinBert/latin-bert/case_studies/pos_tagging/scripts/sequence_reader.py", line 81, in prepare_annotations_from_file
    annotations = read_annotations(filename, tagset, labeled)
  File "/home/circse/latinBert/latin-bert/case_studies/pos_tagging/scripts/sequence_reader.py", line 61, in read_annotations
    data.append(tagset[label])
KeyError: 0
```

What am I doing wrong?
I followed all the step to get the test (on Perseus data) without any error on a "CPU  installation" of Pytorch and the suggested Anaconda environment.

**Comment by dbamman** [comment]
Just pushed a fix for this -- this should be working now.

**Comment by gersh0m** [comment]
yep! It works just fine!
Thank you so much!

**Comment by gersh0m** [comment]
the output file has two column one for the Lemma and one for the PoS, I guess.
But... the lemma field is actually filled with the normalized (lower case) of the input form.
Isn't the prediction about both fields  Lemma and PoS?

**Comment by dbamman** [comment]
Yes, we're only evaluating the Universal Dependency UPOS task, so just the (coarse) part-of-speech tag; the output prediction then includes the lowercased input word form (col 1) and the POS prediction for it (col 2).

**Comment by gersh0m** [comment]
Ok thank you again.
